name: Release CV

on:
  push:
    branches:
    - main

env:
  FILE_PREFIX: "Igor Vasilevskii CV"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v6
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v4
      with:
        compiler: 'pdflatex'
        root_file: |
          *.tex
    - name: Print logs
      if: failure()
      run: |
        ls -la
        cat *.log
    - name: Build png
      run: |
        sudo apt update && sudo apt install -y poppler-utils
        pdftoppm *.pdf "${FILE_PREFIX}" -png -singlefile
    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: build
        path: |
          *.pdf
          *.png

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v6
    - name: Retrieve date
      id: resolve-date
      run: |
        DATE="$(date +'%Y-%m-%d')"
        echo "date=$DATE" >> "$GITHUB_OUTPUT"
    - name: Retrieve Git short SHA
      id: git-short-sha
      run: |
        SHORT_SHA="$(git rev-parse --short HEAD)"
        echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"
    - uses: actions/download-artifact@v7
      with:
        name: build
    - name: Create or update release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true
        tag_name: ${{ steps.resolve-date.outputs.date }}-${{ steps.git-short-sha.outputs.short_sha }}
        files: |
          *.pdf

  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v6
    - name: Download build artifact
      uses: actions/download-artifact@v7
      with:
        name: build
        path: ./pages
    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
